### ISSUE TITLE
new release of intervals (1.8) doesn't work with Python 3.7.0

### ISSUE THREAD

**Issue by gtsambos** [AlexandreDecan/python-intervals#10]
[Here's a gist](https://gist.github.com/gtsambos/fc77bda3f251f1f7264fca30f79fa1b6) showing some of the bugs.

**Comment by AlexandreDecan** [comment]
How did you install the library? According to the output of ``dir(I)``, it seems you're currently using another library that is called ``intervals`` as well, not mine :-)

**Comment by AlexandreDecan** [comment]
Oooh I think I spotted the error: you imported ``interval`` and not ``intervals``.

**Comment by gtsambos** [comment]
Agh, I'm really sorry for bothering you with my silly little typo!! (Thanks for spotting it too...)

**Comment by AlexandreDecan** [comment]
Don't worry :-)
