### ISSUE TITLE
RuntimeWarning

### ISSUE THREAD

**Issue by shinecurve** [AlexandreDecan/python-intervals#11]
intervals.py:538: RuntimeWarning: invalid value encountered in less_equal
  left = (item >= self._lower) if self._left == CLOSED else (item > self._lower)

RuntimeWarning: invalid value encountered in greater
  right = (item <= self._upper) if self._right == CLOSED else (item < self._upper)

Anaconda3 2019.7
win10_1903 x64

**Comment by AlexandreDecan** [comment]
Hello,

Could you please provide the complete traceback and a reproducible example that leads to this issue? 
According to what I see on Google for this RuntimeWarning, the problem seems related to numpy and more specifically to `np.nan`.

Thank you!

**Comment by shinecurve** [comment]
Thank you for your prompt reply. 
After seeing your reply, I checked my code, I've made a mistake.
I did not consider the np.nan in my ndarray.
Sorry for that.

**Comment by AlexandreDecan** [comment]
Glad your issue is solved;)
