### ISSUE TITLE
x.contains(other) ?

### ISSUE THREAD

**Issue by ndvbd** [AlexandreDecan/python-intervals#15]
Are you sure there is this method?
I have "x in y" but not "x.contains(y)"

should be updated in the docs too

**Comment by AlexandreDecan** [comment]
The `contains` method is present in both `AtomicInterval` and `Interval` :)

**Comment by ndvbd** [comment]
Sorry - my mistake, I was confused with the PyInterval documentation...

**Comment by AlexandreDecan** [comment]
No problem :-)
