### ISSUE TITLE
Shouldn

### ISSUE THREAD

**Issue by geeohgeegeeoh** [AlexandreDecan/python-intervals#16]
```
>> import intervals as I
>> x = I.open(int(1), int(3))
>> y = I.open(int(4), int(5))
>> x|y
(1,3)|(4,5)
```

these are open intervals, the bounds are defined as Int instances. So, unlike reals, the two integers abut, there is not an infintity of real points or intervals between them. Surely the result of x|y should be a singleton which is the extend of ```x.left``` and ```y.right``` not the explicit x|y outcome?

If I coerce this as (1,3) | (3,5) it works. So for the bounds *matching* it works. It feels like the difference between open and closed intervals has been lost here.

**Comment by AlexandreDecan** [comment]
Please read the doc, we do NOT support discrete intervals.

**Comment by geeohgeegeeoh** [comment]
Understood. Sorry for the noise on your issues list

My concern is that no interval solution in python appears to support
discreet intervals

**Comment by AlexandreDecan** [comment]
There are some libraries that support discrete intervals, e.g. https://pyinterval.readthedocs.io/en/latest/guide.html

However, they have their own set of issues, and most of them are not maintained anymore...
