### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ehsanmavaei** [AlexandreDecan/python-intervals#17]
hi  Alexandre Decan
I have been using your library and it has been really useful however, I want to know if there is a way to output an interval as an array of numbers?
for example :
print( I.closed(0, 5))  returns something like [0, 1, 2, 3, 4, 5]

**Comment by AlexandreDecan** [comment]
Hello,
Thanks for the feedback! 

Yes, there is a way to output such list of numbers. The library provides an ``iterate`` method that (among other) accepts an `Interval` instance and an `incr`ement. It returns a generator object on which you can iterate as usual:

```python
>>> list(I.iterate(I.closed(0, 5), incr=1))
[0, 1, 2, 3, 4, 5]
```

The documentation for this function is available at https://github.com/AlexandreDecan/python-intervals#discrete-iteration

**Comment by ehsanmavaei** [comment]
> Hello,
> Thanks for the feedback!
> 
> Yes, there is a way to output such list of numbers. The library provides an `iterate` method that (among other) accepts an `Interval` instance and an `incr`ement. It returns a generator object on which you can iterate as usual:
> 
> ```python
> >>> list(I.iterate(I.closed(0, 5), incr=1))
> [0, 1, 2, 3, 4, 5]
> ```
> 
> The documentation for this function is available at https://github.com/AlexandreDecan/python-intervals#discrete-iteration

yeah got it ,it does that too and thank you for replying so fast, I really enjoyed the functionality of this library which is unique its own way . hope you the best

**Comment by AlexandreDecan** [comment]
You're welcome!
