### ISSUE TITLE
Wrong detecting overlaps for contiguous Intervals 

### ISSUE THREAD

**Issue by ssic7i** [AlexandreDecan/python-intervals#2]
.overlaps working wrong when intervals are contiguous
examples:
>>> I.closed(1, 2).overlaps(I.closed(2, 3))
True
>>> I.closed(1, 2).overlaps(I.closedopen(2, 3))
False (should be True)
>>> I.closed(1, 2).overlaps(I.closed(2, I.inf))
False (should be True)
--------------------------
>>> I.closed(2, I.inf).overlaps(I.closed(1,2))
False (should be True)
>>> I.closed(2, 3).overlaps(I.closed(1,2))
True
>>> I.closedopen(2, 3).overlaps(I.closed(1,2))
False (should be True)

**Comment by AlexandreDecan** [comment]
I'm back from holidays. I'll have a look asap. This bug wasn't catch by the test suite because of the `permissive` flag. Sorry for that.

**Comment by AlexandreDecan** [comment]
Bug is fixed in 1.5.4, available in a few minutes on PyPI.
