### ISSUE TITLE
Make empty interval comparable by reference

### ISSUE THREAD

**Issue by justas-** [AlexandreDecan/python-intervals#4]
As it is now we have to instantiate I.empty() to compare if the interval is empty:

> i1 = I.empty()
> i1 == I.empty()
>True
> i1 is I.empty()
> False

In certain applications this can have a significant performance impact. Would it be possible to have a singleton for an empty interval, which would allow checking using "is" operator?

**Comment by AlexandreDecan** [comment]
It's quite unusual in Python to use identity operator (`is`) to support this kind of use case; e.g. with lists:

```python
>>> m = []
>>> m is []
False
```

Why not use `i1.is_empty()` in your case?

**Comment by justas-** [comment]
Good point! I did not know about is_empty() and got used to using sympy's singleton EmptyInterval.

**Comment by AlexandreDecan** [comment]
I hope is_empty() will do the job performances-wise ;-) 

I would be very interested to get your feedback on how python-intervals' performances are in practice. My use cases usually do not exceed tens of intervals, so I don't know if there are bottlenecks.

**Comment by justas-** [comment]
My use case involves simulation with a lot of time intervals. For each set of simulation parameters I calculate ~12 time intervals. Then I check if all of them are valid. If they are - then I calculate one intersection of them all and check again if it is valid (not empty). Compared to sympy I see ~30x improvement using python-intervals.

**Comment by AlexandreDecan** [comment]
Thank you! That's a good news ;-)

**Comment by AlexandreDecan** [comment]
I know this issue is quite old and a "workaround" has been found, but since 1.8.0, `I.empty()` always returns the same instance, so comparing `some_interval == I.empty()` should be nearly as fast than `some_interval.is_empty()`. Notice that `is` operator is still **not** supported (because not all empty intervals are created using `I.empty()`, so we cannot ensure that their `id(...)`'s will be the same!)
