### ISSUE TITLE
[enhancement] Add function is_singleton

### ISSUE THREAD

**Issue by gfitas** [AlexandreDecan/python-intervals#8]
Hello,

I was wondering if it will be possible to add a function that could say if an interval is a singleton or not ? 
For the moment I just did i.lower==i.upper but I found it dirty. A solution with a function is_singleton will be more elegant.

Thank you in advance

**Comment by AlexandreDecan** [comment]
Hello,

That's feasible ;) I've two questions in mind then:

1. Shouldn't we also add `is_left_open`, `is_right_open`, `is_left_closed`, `is_right_closed`, `is_left_bounded`, `is_right_bounded` so we have a "full" set of property checkers?
2. Should we add them as functions, or as methods (e.g. like `i.is_empty`). The latter seems more adequate...

**Comment by AlexandreDecan** [comment]
I'm currently considering making ``lower``, ``left``, ``right`` and ``upper`` available on ``Interval`` instances as well. As such, it won't be required to access the underlying ``AtomicInterval`` instances of an ``Interval`` instance to perform some common checks:

```python
>>> x = I.openclosed(-I.inf, 0)
>>> # Check for left/right closed
>>> x.left is I.CLOSED, x.right is I.CLOSED
(False, True)
>>> # Check if interval is left/right bounded
>>> x.lower is -I.inf, x.upper is I.inf
(True, False)
>>> # Check for singleton
>>> x.lower == x.upper
False

```

Also notice from that example that `I.inf` and `-I.inf` are now singleton objects (so ``==`` is no longer required for them).

**Comment by AlexandreDecan** [comment]
Does the change solve your problem? It allows you to do `i.lower == i.upper` instead of `i.to_atomic().lower == i.to_atomic().upper` or even `i[0].lower == i[-1].upper`. 

I know that you found  `i.lower == i.upper` "ugly", but it is the (second) most obvious piece of code to check for a singleton (the first one being `is_singleton`, but I don't think it really adds value to the library). I'm waiting for your feedback before pushing the changes.

**Comment by AlexandreDecan** [comment]
I merged the changes to master, among other (many) changes that should ease intervals transformations and modifications.

I'll release 1.8.0 tomorrow unless these changes do not solve this issue.
